# Site settings
title: Curious MOFO
twitter_username: viv3kanand
github_username: viv3kanand
description: "Not if, when."
baseurl: ""
url:
future: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
