# Site settings
title: Curious MOFO
email: viv3kanand@gmail.com
twitter_username: viv3kanand
github_username: viv3kanand
linkedin_username: viv3kanand
description: ""
baseurl: ""
url: viv3kanand.github.io
future: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
