# Site settings
title: AWKwaRd Genomics
email: viv3kanand@gmail.com
twitter_username: viv3kanand
github_username: viv3kanand
linkedin_username: viv3kanand
description: ""
baseurl: ""
url: viv3kanand.github.io
google_analytics: UA-134917688-1
future: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
