project:
  type: website
  output-dir: docs

website:
  title: "viv3kanand.github.io"
  navbar:
    background: primary
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom-dark.scss]

editor: visual
#
